set(SOURCES
        src/recompression/parallel_recompression.cpp
        src/recompression/parallel_lock_recompression.cpp
        src/recompression/rlslp.cpp
        src/recompression/parallel_lp_recompression.cpp
        src/recompression/recompression.cpp
        src/recompression/fast_recompression.cpp
        src/recompression/util.cpp
        src/recompression/parallel_order_less_recompression.cpp
        src/recompression/parallel_rnd_recompression.cpp
        src/recompression/lce_query.cpp
        src/recompression/radix_sort.cpp
        src/recompression/parallel_order_great_recompression.cpp
        src/recompression/full_parallel_recompression.cpp
        src/recompression/hash_recompression.cpp
        src/recompression/defs.cpp
        src/recompression/coders/rlslp_rule_sorter.cpp
        src/recompression/coders/coder.cpp
        src/recompression/coders/plain_rlslp_coder.cpp
        src/recompression/coders/plain_fixed_rlslp_coder.cpp
        src/recompression/coders/sorted_rlslp_dr_coder.cpp
        src/recompression/coders/sorted_rlslp_coder.cpp
        src/recompression/io/bitostream.cpp
        src/recompression/io/bitistream.cpp
        src/recompression/generators/text_generator.cpp
        src/recompression/generators/repeated_text_generator.cpp
        src/recompression.cpp
)
set(HEADERS
        include/recompression/parallel_lp_recompression.hpp
        include/recompression/parallel_lock_recompression.hpp
        include/recompression/defs.hpp
        include/recompression/lce_query.hpp
        include/recompression/rlslp.hpp
        include/recompression/recompression.hpp
        include/recompression/parallel_recompression.hpp
        include/recompression/radix_sort.hpp
        include/recompression/parallel_order_less_recompression.hpp
        include/recompression/parallel_rnd_recompression.hpp
        include/recompression/full_parallel_recompression.hpp
        include/recompression/fast_recompression.hpp
        include/recompression/hash_recompression.hpp
        include/recompression/util.hpp
        include/recompression/parallel_order_great_recompression.hpp
        include/recompression/coders/plain_rlslp_coder.hpp
        include/recompression/coders/plain_fixed_rlslp_coder.hpp
        include/recompression/coders/sorted_rlslp_dr_coder.hpp
        include/recompression/coders/sorted_rlslp_coder.hpp
        include/recompression/coders/rlslp_rule_sorter.hpp
        include/recompression/coders/coder.hpp
        include/recompression/io/bitistream.hpp
        include/recompression/io/bitostream.hpp
        include/recompression/generators/text_generator.hpp
        include/recompression/generators/repeated_text_generator.hpp
        include/recompression.hpp
)
